apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw2-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw2
  template:
    metadata:
      labels:
        app: hw2
    spec:
      containers:
      - name: hw2-container
        image: IMAGE_NAME  
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
