apiVersion: v1
kind: Config
clusters:
- name: "645hw2cluster"
  cluster:
    server: "https://52.21.50.237/k8s/clusters/c-m-ql8b7jnn"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GMwTVRVNApORGt4T0RBZUZ3MHlOVEF6TVRBd05UTTFNVGhhRncwek5UQXpNRGd3TlRNMU1UaGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56UXhOVGcwT1RFNE1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRTNMdWFzU21oZWNveApCTm9DVythSHRjUFZ2ODVGOHp0cjFnTHRsV\
      W53b0tnT2wrZDNRc0NpMlJsVmdyRDUxVkNRMFovcWg3WFRPNm43CjZ4V2tSZm1OaktOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      zJqeEN5MWw0aG0zK3Z5ZjdiZi8zU1hzK0wzTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUFnVAowU\
      EY1UGY5WjZWVmxkTGxZOGFFVnd3YnRVdTBFTXhPSmVaeHBWeXltQWlCTkQwREREek5tNXNHQzhQQ\
      mp1RXNIClVHbFRqeTZxNmRldXZtK2RFY1hSMXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "645hw2cluster"
  user:
    token: "kubeconfig-user-64dczwfptc:cjfstl7td8lrn6jh8pcqp2h2mf2pdpl7cx625psh52x9bqfx6xpsq8"


contexts:
- name: "645hw2cluster"
  context:
    user: "645hw2cluster"
    cluster: "645hw2cluster"

current-context: "645hw2cluster"
