apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: hw2  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 
      nodePort: 32345
  type: NodePort
